[package]
name = "sodium_stream"
version = "0.1.0"
authors = ["Maya MacLean"]

[dependencies]
rust_sodium = "0.9.0"
blake2_c = "0.3.1"
openssl = { version = "0.10.11", features = ["vendored"] }
rust-argon2 = "0.3.0"
